import Head from 'next/head'
import Link from 'next/link'
import Moment from 'react-moment'
import styles from '../styles/Home.module.css'

export default function Home({ courses, title = 'Scoreplus' }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {courses.map((course) => (
          <div key={course.id} className={styles.courses__container}>
            <div className={styles.course__card}>
              <Link href={`/course/${course.id}`}>
                <div className={styles.video__container}>Video</div>
              </Link>
              <div className={styles.video__details}>
                <h1>{course.title}</h1>
                <p>{course.description}</p>
                <Moment format='YYYY/MM/DD'>{course.createdAt}</Moment>
                <div className={styles.tags}>
                  {course.tags.split(',').join('   ')}
                </div>
              </div>
            </div>
          </div>
        ))}
      </main>
      <footer className={styles.footer}>
        Developed with 💕 By Shubham Kumar
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(
    'https://eb69c8de-c627-47d4-b0bd-246d961cbfd3.mock.pstmn.io/youtube?class=10th&subject=Maths'
  )
  const courses = await res.json()
  return {
    props: {
      courses,
    },
  }
}
